---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: provider-clusterbook
  description: Crossplane Provider that manages IP reservations and PDNS records via clusterbook REST API
  annotations:
    github.com/project-slug: stuttgart-things/xplane-provider-clusterbook
    backstage.io/techdocs-ref: url:https://github.com/stuttgart-things/xplane-provider-clusterbook/tree/main
    backstage.io/source-location: url:https://github.com/stuttgart-things/xplane-provider-clusterbook
  tags:
    - crossplane
    - provider
    - clusterbook
    - ipam
    - golang
  links:
    - url: https://github.com/stuttgart-things/xplane-provider-clusterbook
      title: GitHub Repository
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
  system: crossplane
