apiVersion: ipreservation.clusterbook.stuttgart-things.com/v1alpha1
kind: IPReservation
metadata:
  name: my-cluster-ip
spec:
  forProvider:
    networkKey: "10.31.103"
    clusterName: "my-cluster"
    count: 1
    createDNS: true
  providerConfigRef:
    name: default
---
apiVersion: ipreservation.clusterbook.stuttgart-things.com/v1alpha1
kind: IPReservation
metadata:
  name: my-cluster-ip-explicit
spec:
  forProvider:
    networkKey: "10.31.103"
    clusterName: "my-cluster"
    ip: "10.31.103.50"
    createDNS: false
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
