apiVersion: clusterbook.stuttgart-things.com/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: default
spec:
  url: "http://clusterbook.clusterbook-system:8080"
---
apiVersion: clusterbook.stuttgart-things.com/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  url: "http://clusterbook.clusterbook-system:8080"
