apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-clusterbook
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/stuttgart-things/provider-clusterbook
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Manages IP reservations and optional PowerDNS records via clusterbook REST API.
spec:
  capabilities:
    - safe-start
